Removed updates 9001, 9002, 9003 per WS2-1209
ASUWebPlatforms/webspark-module-webspark_blocks pull request #121
Opened 2022-02-24 16:04 UTC by chill5-0

WS2-1209 deletes 9001 and 9003 -- I'm adding 9002 for this PR. Let me know if 9002 should remain.

2022-02-25 04:21 UTC, mlsamuelson requested changes
See comment related to retaining most of 9002.

2022-02-25 04:21 UTC, mlsamuelson commented on webspark_blocks.install
> -  _webspark_blocks_revert_module_config();
9002 should remain, but line 41  which does a revert config should be removed:
```
_webspark_blocks_revert_module_config();
```
My rationale is that we want to maintain consistency with removing the basic blocks, but we need to not have a config revert happen until after the background color updates have occurred. 9002 without the config revert line should accomplish that.

2022-02-25 15:45 UTC, chill5-0 commented on webspark_blocks.install
> -  _webspark_blocks_revert_module_config();
Sounds good! New commit added with the changes.

2022-02-26 03:42 UTC, mlsamuelson approved these changes
Thanks @chill5-0 ! Approved.

2022-02-26 03:43 UTC, merged