WS2-1237: Add show borders field for card paragraphs.
ASUWebPlatforms/webspark-module-webspark_blocks pull request #143
Opened 2023-01-09 22:55 UTC by juanmitriatti

2023-01-10 18:31 UTC, juanmitriatti commented
Ticket: https://asudev.jira.com/browse/WS2-1237

2023-01-31 16:43 UTC, mlsamuelson commented
HOLD on merging until after 2.8 hotfix release of WS2

2023-02-09 20:32 UTC, mlsamuelson requested changes

2023-02-09 20:32 UTC, mlsamuelson commented on config/install/core.entity_view_display.paragraph.card.default.yml
> +    region: content
@juanmitriatti Is this sneaking back in after it was removed in the [WS2-1529 PR](https://github.com/ASUWebPlatforms/webspark-module-webspark_blocks/commit/c45b8c94a300551f7457867daf6e43d9af521533#diff-7cce76195417c597939dd9a4465a2ce25e7d3cfd248952c0a29a6c4302d22669L24-L46) ?

I see other instances of the `field_card_link` field being added in these yaml's and I'm concerned it's accidental. Can you please check?

2023-02-09 20:35 UTC, juanmitriatti commented on config/install/core.entity_view_display.paragraph.card.default.yml
> +    region: content
Hi @mlsamuelson 
Let me review please.
Thanks

2023-02-10 22:05 UTC, juanmitriatti commented on config/install/core.entity_view_display.paragraph.card.default.yml
> +    region: content
Hi @mlsamuelson 
I just pushed a commit reverting the field clickable and field card link from this PR.
Thanks

2023-02-13 15:13 UTC, mlsamuelson approved these changes

2023-02-13 15:13 UTC, merged