WS2-1563 - Search form in /system/404 body correctly points to search
ASUWebPlatforms/webspark-module-webspark_blocks pull request #151
Opened 2023-03-22 22:28 UTC by bjdevil21

The issue was that the original code was written for the old GCSE instance, vs. search.asu.edu. Updated the code. Tested locally. Creating a multidev instance with the GetProtected site for Pantheon QA testing.

2023-03-27 23:59 UTC, chill5-0 requested changes, later dismissed
Tested in local 2.8.1 site - note that some sites may have custom 404 pages enabled so the update will not apply to those 404s. The search box correctly redirects to the search.asu.edu site with correct parameters. However, search terms with quotes get cut off where the character starts.

2023-03-28 23:12 UTC, mlsamuelson requested changes

2023-03-28 23:12 UTC, mlsamuelson commented on src/Form/WebsparkBlocksAsuSearchForm.php
> +    $url_host = (Html::escape($_SERVER['HTTP_HOST'])) ?? '';
`asu_brand` module allows sites to optionally configure a local site URL, let's honor that setting when it exists - here's where it's used in that module:
https://github.com/ASUWebPlatforms/webspark-module-asu_brand/blob/main/src/Plugin/Block/AsuBrandHeaderBlock.php#L115-L124

Note: the settings value is just the domain (e.g. `yourdomain.asu.edu`) - and there's an `opt-out` value since some sites don't want the local site search - for instance https://search.asu.edu itself! 

Probably best to do a PR first to asu_brand to create a function that contains the above-linked code into a Drupal helper service method, and then have the `asu_brand` module call that to get the local site url with the `opt-out` logic encapsulated, and then similarly use that helper service over here. Example of how we implemented a helper service in `asu_degree_rfi` module (shared as an example of how to wire a service together, not so much for the content of what those service functions are doing):

* [defining the service](https://github.com/ASUWebPlatforms/webspark-module-asu_degree_rfi/blob/main/asu_degree_rfi.services.yml#L10-L11)
* [defining the helper class and its functions](https://github.com/ASUWebPlatforms/webspark-module-asu_degree_rfi/blob/main/src/AsuDegreeRfiHelperFunctions.php)
* [using one of the helper functions in the module code](https://github.com/ASUWebPlatforms/webspark-module-asu_degree_rfi/blob/main/src/Plugin/Block/AsuDegreeRfiRfiBlock.php#L107)

2023-03-30 23:36 UTC, bjdevil21 commented on src/Form/WebsparkBlocksAsuSearchForm.php
> +    $url_host = (Html::escape($_SERVER['HTTP_HOST'])) ?? '';
I've followed your suggestion (created a new service in asu_brand to use) and it needs another review. 

Also, the ASU Brand project change in webspark-module-asu_brand/ws2-1563 needs to be simultaneously pulled into the asu_brand module (along with the usual cache clear) to test the code.

2023-03-31 21:24 UTC, bjdevil21 commented
@chill5-0 - Even though it's not visible in the browser URL bar, it's being passed into search.asu.edu as an encoded string (only !, *, (, and ) don't get encoded). See screen capture of a log entry below:

![image](https://user-images.githubusercontent.com/2923973/229234327-641e4fde-c226-4b0f-8a3e-62409a06ecb6.png)

 If there's an issue still, it's with  #search.asu.edu.

2023-04-03 21:55 UTC, bjdevil21 commented
This PR should address possible XSS issues (ex. malicious input from the 404 page's search form) up through the redirect. Search.asu.edu is doing the remaining cleanup of the output, per Dave Ornelas and Michael S in the 1130AM meeting today.)

@mlsamuelson - Can you sign off on this PR? Again, this should be approved at the same time as the ASU Brand module PR at https://github.com/ASUWebPlatforms/webspark-module-asu_brand/pull/38.

2023-04-22 00:57 UTC, mlsamuelson requested changes

2023-04-22 00:57 UTC, mlsamuelson commented on src/Form/WebsparkBlocksAsuSearchForm.php
> +    $keyword = \Drupal::service('asu_brand.helper_functions')->encodeURIComponent($keyword);
@bjdevil21 You use the `asu_brand` service before the next line checks if the `asu_brand` module exists. Can you restructure so the code checks first for both usages?

2023-04-28 01:33 UTC, bjdevil21 commented on src/Form/WebsparkBlocksAsuSearchForm.php
> +    $keyword = \Drupal::service('asu_brand.helper_functions')->encodeURIComponent($keyword);
Placed the asu_brand code in the if/then check as requested. Also added local snippet just in case asu_brand isn't installed.

2023-04-28 01:35 UTC, bjdevil21 commented
@mlsamuelson - I accidentally merged the related PR before I finished fixing this one, so if you could, please review this one quickly. :)

2023-04-28 15:08 UTC, mlsamuelson approved these changes

2023-04-28 15:09 UTC, merged